mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=springuser
    - MYSQL_PASSWORD=1903
    - MYSQL_DATABASE=db_mysql
    - MYSQL_ROOT_PASSWORD=1903
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"