package com.project.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/db_mysql") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private AlunoRepository alunoRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody String addNewAluno (@RequestParam String name, @RequestParam String curso) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Aluno aluno = new Aluno();
        aluno.setName(name);
        aluno.setCurso(curso);
        alunoRepository.save(aluno);
        return "Salvo";
    }

    @GetMapping(path = "all")
    public @ResponseBody Iterable<Aluno> getAllAlunos() {
        // This returns a JSON or XML with the users
        return alunoRepository.findAll();
    }
}
